baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "U-PAC 1.01"
theme = "PaperMod"   # Change to "ananke" if preferred

# Site-wide parameters
[params]
  ShowReadingTime = false
  ShowShareButtons = true
  ShowToc = false
  TocOpen = true

# Navigation Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "candidates"
    name = "Candidates"
    url = "/candidates/"
    weight = 2

  [[menu.main]]
    identifier = "volunteer"
    name = "Volunteer"
    url = "/volunteer/"
    weight = 3

  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "/donate/"
    weight = 4

# Output formats for different pages
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

# Markdown and Goldmark settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
