name = "sibi-d1-worker"
main = "src/index.js"
account_id = "8bfd3f60fbdcc89183e9e312fb03e86e"
workers_dev = true
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "SIBIDRIFT_DB"
database_name = "sibidrift.db"
database_id = "aeedccf4-14bb-48f8-91c0-a9023c9f153c"

# [miniflare]
# d1_databases = [
#   { binding = "SIBIDRIFT_DB", path = "/home/anchor/projects/u-pac/u-pac-hugo/sibi-d1-worker/sibidrift.db" }
# ]

[vars]
ENV_MESSAGE = "Loaded on Cloudflare"
ENV = "development"

[build]
# (Any additional build configuration here)
