name = "sibi-d1-worker"
main = "src/index.js"
compatibility_date = "2025-03-10"
workers_dev = true
account_id = "8bfd3f60fbdcc89183e9e312fb03e86e"

[vars]
ENV = "production"  # or just remove entirely if unused

[[kv_namespaces]]
binding = "LEGISLATORS_KV"
id = "bed00144de4b44c0bb6e06218fc8cf80"
preview_id = "795ed60709c94285a32831d3f913efb7"

[[d1_databases]]
binding = "SIBIDRIFT_DB"
database_name = "sibidrift.db"
database_id = "aeedccf4-14bb-48f8-91c0-a9023c9f153c"

[env.production]
workers_dev = false
route = "https://u-pac.org/api/*"

[env.production.vars]
ENV = "production"

[[env.production.kv_namespaces]]
binding = "LEGISLATORS_KV"
id = "bed00144de4b44c0bb6e06218fc8cf80"
preview_id = "795ed60709c94285a32831d3f913efb7"

[[env.production.d1_databases]]
binding = "SIBIDRIFT_DB"
database_name = "sibidrift.db"
database_id = "aeedccf4-14bb-48f8-91c0-a9023c9f153c"
